In [1]:
%pip install numpy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\FernandaCorrea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (2.4.6)
Requirement already satisfied: pandas in C:\Users\FernandaCorrea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\FernandaCorrea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\FernandaCorrea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\FernandaCorrea\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\FernandaCorrea\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import json
import pandas as pd

In [3]:
FILE_PATH = r"C:\Users\FernandaCorrea\Documents\Documentos Belén\Certificado avanzado Data Science - ITBA\Módulo 4 - Data Viz\my_spotify_data (2)\Spotify Account Data\YourLibrary.json"

# Leer el archivo indicando codificación UTF-8
with open(FILE_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

# Convertir la lista "tracks" a DataFrame
Library = pd.DataFrame(data["tracks"])

# Mostrar los primeros 5 registros
print(Library.head())

               artist                   album                track  \
0  The Rolling Stones              Tattoo You  Heaven - Remastered
1           Los Besos  Matemática sentimental               Hoy no
2                 WOS                 TERRAZA              TERRAZA
3           The Smile            Wall Of Eyes   Friend Of A Friend
4           Los Besos  Matemática sentimental               Limeña

                                    uri
0  spotify:track:0QVJsWtmgj9SWZaLYiX2i3
1  spotify:track:0KleRPmITxRwrf1YOwAYVy
2  spotify:track:6cLWKCBNawunqBHmyzdG7v
3  spotify:track:4lTLmo9aTyMJ1SoHa63WA6
4  spotify:track:3vM93cAeHAiQvtmUc8OKTi

In [ ]:
# Ranking de artistas en mi librería de Spotify según la cantidad de canciones que tengo de cada uno
ranking_artistas = (
    Library.groupby("artist")
    .size()
    .reset_index(name="cantidad_canciones")
    .sort_values(by="cantidad_canciones", ascending=False)
)

ranking_artistas

                    artist  cantidad_canciones
47           Charly García                  29
22             Babasonicos                  21
170  Luis Alberto Spinetta                  16
255             Serú Girán                  13
157              Los Besos                  12
..                     ...                 ...
295      The White Stripes                   1
296             Thundercat                   1
300                   Turf                   1
302             Underworld                   1
320    my bloody valentine                   1

[321 rows x 2 columns]

In [9]:
# Rutas de los archivos
FILE_PATH_2 = r"C:\Users\FernandaCorrea\Documents\Documentos Belén\Certificado avanzado Data Science - ITBA\Módulo 4 - Data Viz\my_spotify_data (2)\Spotify Account Data\StreamingHistory_music_0.json"
FILE_PATH_3 = r"C:\Users\FernandaCorrea\Documents\Documentos Belén\Certificado avanzado Data Science - ITBA\Módulo 4 - Data Viz\my_spotify_data (2)\Spotify Account Data\StreamingHistory_music_1.json"

with open(FILE_PATH_2, "r", encoding="utf-8") as f:
    data_0 = json.load(f)

with open(FILE_PATH_3, "r", encoding="utf-8") as f:
    data_1 = json.load(f)

# Cargar en DataFrames y concatenar
df0 = pd.DataFrame(data_0)
df1 = pd.DataFrame(data_1)

streaming_history = pd.concat([df0, df1], ignore_index=True)

# Convertir milisegundos a minutos para facilitar el análisis
streaming_history["minutesPlayed"] = (
    streaming_history["msPlayed"] / 60000
).round(2)

# Mostrar las primeras filas de la tabla combinada
streaming_history.head()

,endTime,artistName,trackName,msPlayed,minutesPlayed
0,2025-08-19 19:46,Arctic Monkeys,Brick By Brick,7603,0.13
1,2025-08-19 22:44,Green Day,Jesus of Suburbia,518040,8.63
2,2025-08-20 12:09,MissLupe,Nuestros Besos,63466,1.06
3,2025-08-21 12:08,Gauchito Club,La Pibita,50130,0.84
4,2025-08-21 14:10,Radiohead,Let Down,548,0.01

In [10]:
# Contar reproducciones para TODOS los artistas ordenados de mayor a menor
ranking_completo = (
    streaming_history["artistName"].value_counts().reset_index()
)
ranking_completo.columns = ["Artista", "Cantidad_de_Reproducciones"]

# Ver el DataFrame completo
ranking_completo

                                     Artista  Cantidad_de_Reproducciones
0                                 Charli xcx                         433
1                                  Bad Bunny                         432
2                                    ROSALÍA                         428
3                                Mac DeMarco                         342
4    Patricio Rey y sus Redonditos de Ricota                         315
..                                       ...                         ...
715                             Nia Archives                           1
716                             SIENNA SPIRO                           1
717                           Kendrick Lamar                           1
718                               Lola Young                           1
719                       Corinne Bailey Rae                           1

[720 rows x 2 columns]